### ISSUE TITLE
Remove sex-homosexuality from OARS

### ISSUE THREAD

**Issue by danirabbit** [hughsie/oars#40]
There are already tags for nudity, sexual appearance, and sexual themes. It seems to me that the only reason to specifically call out homosexuality is for the purposes of discrimination.

I understand that the current position is that without this rating it wouldn't be possible to distribute some software in some countries. But, I strongly believe this stance should be reconsidered.

There is an opportunity here to stand up for what is right and refuse to comply with those who would encourage this kind of discrimination. Yes that would make OARS unusable in certain countries, but how is that any different from the common software licenses we use which enforce the essential freedoms we believe in at the expense of making our software unusable for some?

The alternative is knowing releasing software that will be used for the express and sole purpose of discriminating against people. **This tag's only purpose is to suppress human rights.**

**Comment by hughsie** [comment]
Couldn't you argue the same about the majority of the tags in OARS?

**Comment by cassidyjames** [comment]
Alcohol references, sharing the user's location, and depicting fantasy violence aren't really in the same category as human rights, though, and I don't think comparing them is productive. Something we've discussed at elementary is if some of the cultural sensitivity questions (specifically homosexuality, at least) could be dropped and relegated to country-specific prefixes if software wishes to be distributed in those countries; for example, `x-fakecountry-homosexuality`, and leave it up to those countries to determine what needs to be clarified and how. 

Otherwise I fear the natural path for OARS is to attempt to be a global framework of every country's specific laws, codifying compliance with every single one. If it's illegal to wear blue on Saturdays in some obscure city, do we need to ensure every single app is documenting whether it depicts this?

To be clear, our recommendation at elementary is for app developers to omit this tag as we feel it is both discriminatory and redundant with the other tags—and we will continue to do so. It would just be nice to not have to explain to developers why recommended tools like OARS are asking them questions about homosexuality, which they've expressed feels odd at best and discriminatory at worst.

**Comment by cassidyjames** [comment]
Another simpler option that could at least improve the situation is if the OARS generator itself could provide more context here around this question. Instead of just, "Homosexuality: Defined as sexual attraction to people of one's own sex. This is an v1.1 cultural sensitivity question," this could be an opportunity to specify something like: "This question is designed to allow software distribution to comply with local laws. OARS as a project does not agree with discrimination based on sexual orientation and this question may be omitted, though your software may be restricted from distribution if local laws require its disclosure."  

I don't think that necessarily resolves this issue completely, but could be a step in the right direction.

**Comment by hughsie** [comment]
> If it's illegal to wear blue on Saturdays in some obscure city

If it was illegal for software to depict somebody wearing blue on Saturdays and that country had 20 million potential customers, then this would be an allowed question. OARS doesn't require the questions make sense, and trying to overlay western justifications on something that has a raison-d'etre of making it possible to distribute software to countries that most people (including me) find morally repugnant.

> our recommendation at elementary is for app developers to omit this tag

Yes, that's fine. This might be an issue if you try selling to certain less than awesome governments but I don't think this is something you're probably worried about.

**Comment by hughsie** [comment]
> This question is designed to allow software distribution to comply with local laws. OARS as a project does not agree with discrimination based on sexual orientation and this question may be omitted, though your software may be restricted from distribution if local laws require its disclosure

FWIW, I'd be 100% okay with something like that.

**Comment by hughsie** [comment]
> and this question may be omitted

maybe instead "_and all the cultural sensitivity questions may be omitted_" as it's perfectly find to do an OARS 1.0 without the extra questions in 1.1

**Comment by hughsie** [comment]
I'd of course like a pull request if that's not too cheeky; I'm crap with prose and this is somewhat sensitive prose.

**Comment by cassidyjames** [comment]
I guess that also raises the question of implementation: currently, if a tag is omitted it is assumed to be `none`. So should we actively recommend people use v1.0 if they want to omit these questions?

**Comment by hughsie** [comment]
> So should we actively recommend people use v1.0 if they want to omit these questions

Definitely yes.

**Comment by GabTheBab** [comment]
How about grouping homosexuality in a single attribute about sexuality in general? This should be legal countries that require this without contributing to oppression.

**Comment by hughsie** [comment]
> How about grouping homosexuality in a single attribute about sexuality in general

Not going to work, sorry. Some countries are perfectly happy with explicit heterosexual content of any kind, but the penalty for viewing any kind of homosexual content would be something like the death penalty. It's clearly unfair, and makes my head boggle, but unfortunately the world is a horrible place.

**Comment by jakibaki** [comment]
> Not going to work, sorry. Some countries are perfectly happy with explicit heterosexual content of any kind, but the penalty for viewing any kind of homosexual content would be something like the death penalty. It's clearly unfair, and makes my head boggle, but unfortunately the world is a horrible place.

Frankly, that's bullshit.

The obvious solution here is to flag/hide all romantic content including heterosexual one in those countries if you must comply with their laws.  
Anything else is actively contributing to oppression.

**Comment by hughsie** [comment]
Okay, we've resorted to swearing now, so closing this issue. However, @cassidyjames I'm happy to review a pull request with your suggestions.
